### ISSUE TITLE
Tooltip stays behind when the window is destroyed

### ISSUE THREAD

**Issue by 8k84** [gnikit/tkinter-tooltip#59]
I have a tooltip assigned to a widget in a window. If the window is destroyed when the tooltip is displayed, the tooltip stays on.

**Comment by gnikit** [comment]
Can you post a minimal working example that reproduces this behaviour?

**Comment by gnikit** [comment]
For us to be on the same page you will have to post a [Minimal Reproducible Example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) otherwise I am just guessing. Take your time and update the Issue description with some code whenever you have the time, there is no rush.

I am working on a PR that auto?destroys the tooltip, it sounds like that is something you would find useful.
I will ping you when I get something working.

**Comment by gnikit** [comment]
Closing this as stale.
